version: "2.2"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - ./backend:/app
    restart: always

networks:
  default:
    name: sample_node_network